//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./WeirdoGrammar.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IWeirdoGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class WeirdoGrammarBaseListener : IWeirdoGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] WeirdoGrammarParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] WeirdoGrammarParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] WeirdoGrammarParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] WeirdoGrammarParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.function_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_name([NotNull] WeirdoGrammarParser.Function_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.function_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_name([NotNull] WeirdoGrammarParser.Function_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.function_arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_arg([NotNull] WeirdoGrammarParser.Function_argContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.function_arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_arg([NotNull] WeirdoGrammarParser.Function_argContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.function_call_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_call_expression([NotNull] WeirdoGrammarParser.Function_call_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.function_call_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_call_expression([NotNull] WeirdoGrammarParser.Function_call_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.function_icall_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_icall_expression([NotNull] WeirdoGrammarParser.Function_icall_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.function_icall_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_icall_expression([NotNull] WeirdoGrammarParser.Function_icall_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.push_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPush_expression([NotNull] WeirdoGrammarParser.Push_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.push_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPush_expression([NotNull] WeirdoGrammarParser.Push_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.popl_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPopl_expression([NotNull] WeirdoGrammarParser.Popl_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.popl_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPopl_expression([NotNull] WeirdoGrammarParser.Popl_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.argument_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument_expression([NotNull] WeirdoGrammarParser.Argument_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.argument_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument_expression([NotNull] WeirdoGrammarParser.Argument_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.string_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_literal([NotNull] WeirdoGrammarParser.String_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.string_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_literal([NotNull] WeirdoGrammarParser.String_literalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.global_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobal_directive([NotNull] WeirdoGrammarParser.Global_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.global_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobal_directive([NotNull] WeirdoGrammarParser.Global_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.entrypoint_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntrypoint_directive([NotNull] WeirdoGrammarParser.Entrypoint_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.entrypoint_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntrypoint_directive([NotNull] WeirdoGrammarParser.Entrypoint_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] WeirdoGrammarParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] WeirdoGrammarParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.print_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_statement([NotNull] WeirdoGrammarParser.Print_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.print_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_statement([NotNull] WeirdoGrammarParser.Print_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_statement([NotNull] WeirdoGrammarParser.If_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_statement([NotNull] WeirdoGrammarParser.If_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.arg_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArg_list([NotNull] WeirdoGrammarParser.Arg_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.arg_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArg_list([NotNull] WeirdoGrammarParser.Arg_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] WeirdoGrammarParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] WeirdoGrammarParser.FunctionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
