//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./WeirdoGrammar.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="WeirdoGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public interface IWeirdoGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] WeirdoGrammarParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] WeirdoGrammarParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] WeirdoGrammarParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] WeirdoGrammarParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_name([NotNull] WeirdoGrammarParser.Function_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_name([NotNull] WeirdoGrammarParser.Function_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.function_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_arg([NotNull] WeirdoGrammarParser.Function_argContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.function_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_arg([NotNull] WeirdoGrammarParser.Function_argContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.function_call_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_call_expression([NotNull] WeirdoGrammarParser.Function_call_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.function_call_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_call_expression([NotNull] WeirdoGrammarParser.Function_call_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.function_icall_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_icall_expression([NotNull] WeirdoGrammarParser.Function_icall_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.function_icall_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_icall_expression([NotNull] WeirdoGrammarParser.Function_icall_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.push_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPush_expression([NotNull] WeirdoGrammarParser.Push_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.push_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPush_expression([NotNull] WeirdoGrammarParser.Push_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.popl_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPopl_expression([NotNull] WeirdoGrammarParser.Popl_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.popl_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPopl_expression([NotNull] WeirdoGrammarParser.Popl_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.argument_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument_expression([NotNull] WeirdoGrammarParser.Argument_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.argument_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument_expression([NotNull] WeirdoGrammarParser.Argument_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_literal([NotNull] WeirdoGrammarParser.String_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_literal([NotNull] WeirdoGrammarParser.String_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.global_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobal_directive([NotNull] WeirdoGrammarParser.Global_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.global_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobal_directive([NotNull] WeirdoGrammarParser.Global_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.entrypoint_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntrypoint_directive([NotNull] WeirdoGrammarParser.Entrypoint_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.entrypoint_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntrypoint_directive([NotNull] WeirdoGrammarParser.Entrypoint_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] WeirdoGrammarParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] WeirdoGrammarParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.print_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint_statement([NotNull] WeirdoGrammarParser.Print_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.print_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint_statement([NotNull] WeirdoGrammarParser.Print_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_statement([NotNull] WeirdoGrammarParser.If_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_statement([NotNull] WeirdoGrammarParser.If_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.arg_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg_list([NotNull] WeirdoGrammarParser.Arg_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.arg_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg_list([NotNull] WeirdoGrammarParser.Arg_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WeirdoGrammarParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] WeirdoGrammarParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WeirdoGrammarParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] WeirdoGrammarParser.FunctionContext context);
}
